apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asteroids.fullname" . }}-secret
  labels:
    {{- include "asteroids.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ include "asteroids.postgresql.password" . | b64enc | quote }}
