---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "asteroids.frontend.fullname" . }}
  labels:
    {{- include "asteroids.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "asteroids.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "asteroids.backend.fullname" . }}
  labels:
    {{- include "asteroids.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "asteroids.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
