apiVersion: v2
name: asteroids
description: A classic Asteroids game with high score persistence
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-org/asteroids-k8s
sources:
  - https://github.com/your-org/asteroids-k8s
maintainers:
  - name: Your Name
    email: your-email@domain.com
keywords:
  - game
  - asteroids
  - html5
  - javascript
  - nodejs
  - postgresql
annotations:
  category: Games
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
